### ISSUE TITLE
建议VideoPlayerController可以在创建playerWidget的时候传入 [Advice Report]

### ISSUE THREAD

**Issue by z234009184** [chudongvip/awesome_video_player#12]
作者您好.
希望可以动态的通过代码来控制视频, 如 play, pause, seek...  
建议把VideoPlayerController 暴露出来

**Comment by chudongvip** [comment]
> VideoPlayerController 暴露出来

`oninit`回调会把VideoPlayerController 暴露出来，你可以进行相对应的操作，下一版本还会支持倍速功能
