### ISSUE TITLE
切换dataSource 视频url地址无效

### ISSUE THREAD

**Issue by z234009184** [chudongvip/awesome_video_player#13]
您好, 
当我在
```
...省略部分代码
AwsomeVideoPlayer(
      url,
);
...省略部分代码
setState(() {
      url = "https://other_video.mp4";
});
```
切换url之后 视频并没有重新播放,而是接着播放之前的url链接的视频.
请问怎么操作可以切换当前的视频

**Comment by chudongvip** [comment]
> 视频并没有重新播放,而是接着播放之前的url链接的视频.
> 请问怎么操作可以切换当前的视频

```
    /// 更改视频播放链接DMEO
    // Future.delayed(Duration(seconds: 10), () {
    //   setState(() {
    //     videoUrl = "";
    //     Future.delayed(Duration(milliseconds: 100), () {
    //       setState(() {
    //         videoUrl = "https://www.runoob.com/try/demo_source/movie.mp4";
    //       });
    //     });
    //   });
    // });
```

**Comment by z234009184** [comment]
> > 视频并没有重新播放,而是接着播放之前的url链接的视频.
> > 请问怎么操作可以切换当前的视频
> 
> ```
>     /// 更改视频播放链接DMEO
>     // Future.delayed(Duration(seconds: 10), () {
>     //   setState(() {
>     //     videoUrl = "";
>     //     Future.delayed(Duration(milliseconds: 100), () {
>     //       setState(() {
>     //         videoUrl = "https://www.runoob.com/try/demo_source/movie.mp4";
>     //       });
>     //     });
>     //   });
>     // });
> ```

当视频已经开始播放了, 在按钮点击事件中 调用如上代码, 发现没有效果,视频还是不会切换

**Comment by z234009184** [comment]
> > 视频并没有重新播放,而是接着播放之前的url链接的视频.
> > 请问怎么操作可以切换当前的视频
> 
> ```
>     /// 更改视频播放链接DMEO
>     // Future.delayed(Duration(seconds: 10), () {
>     //   setState(() {
>     //     videoUrl = "";
>     //     Future.delayed(Duration(milliseconds: 100), () {
>     //       setState(() {
>     //         videoUrl = "https://www.runoob.com/try/demo_source/movie.mp4";
>     //       });
>     //     });
>     //   });
>     // });
> ```

感谢作者, 的确是这样, 是我代码的问题.
