### ISSUE TITLE
视频快进快退手势拖动, 进度条快进快退速度可以调节吗?

### ISSUE THREAD

**Issue by z234009184** [chudongvip/awesome_video_player#15]
作者您好
视频快进快退手势拖动, 进度条快进快退速度可以调节吗? 目前快进快退, 进度条变化很慢, 亮度和音量也是一样

**Comment by chudongvip** [comment]
> 作者您好
> 视频快进快退手势拖动, 进度条快进快退速度可以调节吗? 目前快进快退, 进度条变化很慢, 亮度和音量也是一样

好的，我开放参数给你调节，谢谢反馈

**Comment by chudongvip** [comment]
> > 作者您好
> > 视频快进快退手势拖动, 进度条快进快退速度可以调节吗? 目前快进快退, 进度条变化很慢, 亮度和音量也是一样
> 
> 好的，我开放参数给你调节，谢谢反馈

I'll fixed this bug with the version 1.0.7
