### ISSUE TITLE
Cannot use the package!

### ISSUE THREAD

**Issue by alr2413** [chudongvip/awesome_video_player#18]
Hi,

I have successfully add this package to my project, however when I try to run the install command the following error was occurred:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':screen'.
> Could not resolve all artifacts for configuration ':screen:classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.jar
   > Could not find builder.jar (com.android.tools.build:builder:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/builder-3.3.1.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.3.1/tracker-26.3.1.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.3.1/shared-26.3.1.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.1/crash-26.3.1.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.3.1/lint-gradle-api-26.3.1.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.3.1/gradle-api-3.3.1.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.3.1/databinding-compiler-common-3.3.1.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.1/manifest-merger-26.3.1.jar
   > Could not find sdk-common.jar (com.android.tools:sdk-common:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.3.1/sdk-common-26.3.1.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.3.1/builder-test-api-3.3.1.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.1/sdklib-26.3.1.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.3.1/layoutlib-api-26.3.1.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.3.1/dvlib-26.3.1.jar
   > Could not find repository.jar (com.android.tools:repository:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.3.1/repository-26.3.1.jar
   > Could not find common.jar (com.android.tools:common:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.3.1/common-26.3.1.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.3.1/builder-model-3.3.1.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.1/protos-26.3.1.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.1/apkzlib-3.3.1.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.1/apksig-3.3.1.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.1/annotations-26.3.1.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.1/databinding-common-3.3.1.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.1/baseLibrary-3.3.1.jar
> Could not get unknown property 'android' for project ':screen' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin awsome_video_player...
Running Gradle task 'assembleAarRelease'...
Unzipping /Users/alireza/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1-all.zip to /Users/alireza/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Exception: The plugin awsome_video_player could not be built due to the issue above.

**Comment by chudongvip** [comment]
Did you open your project with AndroidStudio，There'll automatic installation some required or built-in things.

**Comment by chudongvip** [comment]
> Hi,
> 
> I have successfully add this package to my project, however when I try to run the install command the following error was occurred:
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   A problem occurred configuring project ':screen'.
> 
> > Could not resolve all artifacts for configuration ':screen:classpath'.
> > Could not find gradle.jar (com.android.tools.build:gradle:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.jar
> > Could not find builder.jar (com.android.tools.build:builder:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/builder-3.3.1.jar
> > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.3.1/tracker-26.3.1.jar
> > Could not find shared.jar (com.android.tools.analytics-library:shared:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.3.1/shared-26.3.1.jar
> > Could not find crash.jar (com.android.tools.analytics-library:crash:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.1/crash-26.3.1.jar
> > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.3.1/lint-gradle-api-26.3.1.jar
> > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.3.1/gradle-api-3.3.1.jar
> > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.3.1/databinding-compiler-common-3.3.1.jar
> > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.1/manifest-merger-26.3.1.jar
> > Could not find sdk-common.jar (com.android.tools:sdk-common:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.3.1/sdk-common-26.3.1.jar
> > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.3.1/builder-test-api-3.3.1.jar
> > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.jar
> > Could not find sdklib.jar (com.android.tools:sdklib:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.1/sdklib-26.3.1.jar
> > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.3.1/layoutlib-api-26.3.1.jar
> > Could not find dvlib.jar (com.android.tools:dvlib:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.3.1/dvlib-26.3.1.jar
> > Could not find repository.jar (com.android.tools:repository:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.3.1/repository-26.3.1.jar
> > Could not find common.jar (com.android.tools:common:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/common/26.3.1/common-26.3.1.jar
> > Could not find builder-model.jar (com.android.tools.build:builder-model:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.3.1/builder-model-3.3.1.jar
> > Could not find protos.jar (com.android.tools.analytics-library:protos:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.1/protos-26.3.1.jar
> > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.1/apkzlib-3.3.1.jar
> > Could not find apksig.jar (com.android.tools.build:apksig:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.1/apksig-3.3.1.jar
> > Could not find annotations.jar (com.android.tools:annotations:26.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.1/annotations-26.3.1.jar
> > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.1/databinding-common-3.3.1.jar
> > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.3.1).
> > Searched in the following locations:
> > https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.1/baseLibrary-3.3.1.jar
> > Could not get unknown property 'android' for project ':screen' of type org.gradle.api.Project.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 10s
> The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
> Building plugin awsome_video_player...
> Running Gradle task 'assembleAarRelease'...
> Unzipping /Users/alireza/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1-all.zip to /Users/alireza/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx
> 
> Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> at java.util.zip.ZipFile.open(Native Method)
> at java.util.zip.ZipFile.(ZipFile.java:225)
> at java.util.zip.ZipFile.(ZipFile.java:155)
> at java.util.zip.ZipFile.(ZipFile.java:169)
> at org.gradle.wrapper.Install.unzip(Install.java:214)
> at org.gradle.wrapper.Install.access$600(Install.java:27)
> at org.gradle.wrapper.Install$1.call(Install.java:74)
> at org.gradle.wrapper.Install$1.call(Install.java:48)
> at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> at org.gradle.wrapper.Install.createDist(Install.java:48)
> at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 
> Exception: The plugin awsome_video_player could not be built due to the issue above.

![like this](https://user-images.githubusercontent.com/31001856/78956101-d8326d80-7b13-11ea-9c03-ba55b8092001.png)

**Comment by alr2413** [comment]
No, I'm using Intellij IDEA. Is your package compatible with android X? 
Note that, there is the following exception in the logcat section : "The built failed likely due to AndroidX incompatibilities in a plugin."
Thanks for your fast response.

**Comment by chudongvip** [comment]
> No, I'm using Intellij IDEA. Is your package compatible with android X?
> Note that, there is the following exception in the logcat section : "The built failed likely due to AndroidX incompatibilities in a plugin."
> Thanks for your fast response.

yes, it compatible with android X. if you have any questions, please let me know.
