### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by YeFei572** [chudongvip/awesome_video_player#2]
用了一下大佬的库, 给几点建议:
1. 取消播放键, 因为双击就是播放键, 三个键占用的位子太挤了, 经常点不到自己想点的键, 目前我用的是改变按钮大小, 直接给播放键的size为1;
2. 播放进度条点击的时候经常点击不到, 主要是太窄了,建议点击阴影部分也触发, 因为那部分不是经常点击,所以修改后不会影像整体的体验,反而更加方便用户想要快进到哪个点.或者直接可以自定义进度条的宽度.让用户自己控制宽度;
3. 给是否全屏播放一个回调, 因为在一个有appBar的情况全屏播放会出现appBar,如果有回调可以隐藏appBar.

整体感觉这个库很棒. 谢谢作者!

**Comment by chudongvip** [comment]
> 用了一下大佬的库, 给几点建议:
> 
> 1. 取消播放键, 因为双击就是播放键, 三个键占用的位子太挤了, 经常点不到自己想点的键, 目前我用的是改变按钮大小, 直接给播放键的size为1;
> 2. 播放进度条点击的时候经常点击不到, 主要是太窄了,建议点击阴影部分也触发, 因为那部分不是经常点击,所以修改后不会影像整体的体验,反而更加方便用户想要快进到哪个点.或者直接可以自定义进度条的宽度.让用户自己控制宽度;
> 3. 给是否全屏播放一个回调, 因为在一个有appBar的情况全屏播放会出现appBar,如果有回调可以隐藏appBar.
> 
> 整体感觉这个库很棒. 谢谢作者!



> 用了一下大佬的库, 给几点建议:
> 
> 1. 取消播放键, 因为双击就是播放键, 三个键占用的位子太挤了, 经常点不到自己想点的键, 目前我用的是改变按钮大小, 直接给播放键的size为1;
> 2. 播放进度条点击的时候经常点击不到, 主要是太窄了,建议点击阴影部分也触发, 因为那部分不是经常点击,所以修改后不会影像整体的体验,反而更加方便用户想要快进到哪个点.或者直接可以自定义进度条的宽度.让用户自己控制宽度;
> 3. 给是否全屏播放一个回调, 因为在一个有appBar的情况全屏播放会出现appBar,如果有回调可以隐藏appBar.
> 
> 整体感觉这个库很棒. 谢谢作者!

**Comment by chudongvip** [comment]
谢谢你的建议和支持，下面我回答一下你的3个问题：
1. 底部控制拦的所有元素都可以增删、排序的，只要在`itemList`中添加或删除元素或调整位置；
2. 这个建议我先保留，你可以通过手势进行快进和快退或拖拽进度条按钮，你可以可以设置进度条的高度以及按钮的高度来达到易操作的效果；
3. 关于全屏回调，我会在1.0.6这个版本加上，请期待；

再次感谢您的支持和建议 ，我会毫无保留的做好这个播放器的！

**Comment by chudongvip** [comment]
谢谢你的建议和支持，下面我回答一下你的3个问题：

1. 底部控制拦的所有元素都可以增删、排序的，只要在itemList中添加或删除元素或调整位置；
2. 这个建议我先保留，你可以通过手势进行快进和快退或拖拽进度条按钮，你可以可以设置进度条的高度以及按钮的高度来达到易操作的效果；
3. 关于全屏回调，我会在1.0.6这个版本加上，请期待；

再次感谢您的支持和建议 ，我会毫无保留的做好这个播放器的

**Comment by chudongvip** [comment]
已经发布，请注意查看

**Comment by YeFei572** [comment]
非常棒, 谢谢

**Comment by YeFei572** [comment]
另外还有个事请想请教一下, 目前咱这个库是否支持预加载? 意思就是我暂停播放, 暂停的时候就已经把后续的全部下载下来了, 我目前播放的是m3u8文件, 好像暂停也不见缓冲进度前进

**Comment by chudongvip** [comment]
m3u8 应该做不到预加载，因为他这是切片加载


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YeFei572"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 下午5:31
收件人:&nbsp;"chudongvip/awsome_video_player"<awsome_video_player@noreply.github.com&gt;;
抄送:&nbsp;"roc丶cheam"<604748948@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [chudongvip/awsome_video_player] 建议 (#2)




另外还有个事请想请教一下, 目前咱这个库是否支持预加载? 意思就是我暂停播放, 暂停的时候就已经把后续的全部下载下来了, 我目前播放的是m3u8文件, 好像暂停也不见缓冲进度前进
