### ISSUE TITLE
[Bug Report]全屏报错

### ISSUE THREAD

**Issue by slimcheng** [chudongvip/awesome_video_player#21]
系统：安卓8.0.0
插件版本：1.0.8

```
E/flutter ( 4166): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method SystemChrome.forceOrientation on channel sososdk.github.com/orientation)

E/flutter ( 4166): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)

E/flutter ( 4166):  < asynchronous suspension >

E/flutter ( 4166): #1      OrientationPlugin.forceOrientation (package:orientation/orientation.dart:35:26)

E/flutter ( 4166): #2      _AwsomeVideoPlayerState.toggleFullScreen (package:awsome_video_player/src/video.dart:342:25)

E/flutter ( 4166): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
```

**Comment by chudongvip** [comment]
> 系统：安卓8.0.0
> 插件版本：1.0.8
> 
> ```
> E/flutter ( 4166): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method SystemChrome.forceOrientation on channel sososdk.github.com/orientation)
> 
> E/flutter ( 4166): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> 
> E/flutter ( 4166):  < asynchronous suspension >
> 
> E/flutter ( 4166): #1      OrientationPlugin.forceOrientation (package:orientation/orientation.dart:35:26)
> 
> E/flutter ( 4166): #2      _AwsomeVideoPlayerState.toggleFullScreen (package:awsome_video_player/src/video.dart:342:25)
> 
> E/flutter ( 4166): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> ```

全屏需要通过onfullscreen回调，隐藏掉页面掉其他元素，这个会在今后的几个版本中优化，最快这个周末完成

**Comment by slimcheng** [comment]
> > 系统：安卓8.0.0
> > 插件版本：1.0.8
> > ```
> > E/flutter ( 4166): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method SystemChrome.forceOrientation on channel sososdk.github.com/orientation)
> > 
> > E/flutter ( 4166): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> > 
> > E/flutter ( 4166):  < asynchronous suspension >
> > 
> > E/flutter ( 4166): #1      OrientationPlugin.forceOrientation (package:orientation/orientation.dart:35:26)
> > 
> > E/flutter ( 4166): #2      _AwsomeVideoPlayerState.toggleFullScreen (package:awsome_video_player/src/video.dart:342:25)
> > 
> > E/flutter ( 4166): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> > ```
> 
> 全屏需要通过onfullscreen回调，隐藏掉页面掉其他元素，这个会在今后的几个版本中优化，最快这个周末完成

你好，不是这个问题，是直接报错了，没有进到回调方法里，报错信息如上

**Comment by chudongvip** [comment]
> > > 系统：安卓8.0.0
> > > 插件版本：1.0.8
> > > ```
> > > E/flutter ( 4166): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method SystemChrome.forceOrientation on channel sososdk.github.com/orientation)
> > > 
> > > E/flutter ( 4166): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> > > 
> > > E/flutter ( 4166):  < asynchronous suspension >
> > > 
> > > E/flutter ( 4166): #1      OrientationPlugin.forceOrientation (package:orientation/orientation.dart:35:26)
> > > 
> > > E/flutter ( 4166): #2      _AwsomeVideoPlayerState.toggleFullScreen (package:awsome_video_player/src/video.dart:342:25)
> > > 
> > > E/flutter ( 4166): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> > > ```
> > 
> > 
> > 全屏需要通过onfullscreen回调，隐藏掉页面掉其他元素，这个会在今后的几个版本中优化，最快这个周末完成
> 
> 你好，不是这个问题，是直接报错了，没有进到回调方法里，报错信息如上

依赖没装好，或者是平台的问题，等我修复把，或者你用as打开项目，看看会不会安装一些插件

**Comment by slimcheng** [comment]
嗯，非常感谢，试了下debug不行，但是release是好的

**Comment by slimcheng** [comment]
补充一下
后来自定义UI的时候，封装到一个单独的Widget里面后全屏功能可以了。效果很棒😄

**Comment by frankyvij** [comment]
Hello. I have the similar problem. When I click on full screen icon, the screen changes orientation to Landscape mode; but it does not go to full-screen mode. I can still scroll. Please note that full-screen works perfectly fine with chewie.

**Comment by chudongvip** [comment]
> Hello. I have the similar problem. When I click on full screen icon, the screen changes orientation to Landscape mode; but it does not go to full-screen mode. I can still scroll. Please note that full-screen works perfectly fine with chewie.

It will be optimized in a later release, and now you can hide other widget by calling back `onfullscreen`.

see [example](https://github.com/chudongvip/awesome_video_player/blob/master/example/lib/main.dart):
line: 40 and 360.
