### ISSUE TITLE
请教怎么监控到组件里的videocontroller，还有切换数据源的时候，原来的还在播放咋办。

### ISSUE THREAD

**Issue by twpDesigner** [chudongvip/awesome_video_player#25]

**Comment by chudongvip** [comment]
> _No description provided._

这个是调试模式下的热重载，正式打包之后是不会触发的，请放心使用。
PS: 马上有新的版本伤心，体验更好，你说的这些问题都会解决掉，今天会发一个bate版本，详情见github分支

**Comment by twpDesigner** [comment]
好的，谢谢




| |
shadowsstt
邮箱：shadowsstt@163.com
|

Signature is customized by Netease Mail Master

在2020年04月25日 19:32，初冬 写道：

No description provided.

这个是调试模式下的热重载，正式打包之后是不会触发的，请放心使用。
PS: 马上有新的版本伤心，体验更好，你说的这些问题都会解决掉，今天会发一个bate版本，详情见github分支
