### ISSUE TITLE
PLEASE ADD THIS FUNCTIONALITY

### ISSUE THREAD

**Issue by MeTubeapp** [chudongvip/awesome_video_player#33]
1-ADD A COVER LOCK
2-GESTURE ANIMATION UI FOR BRIGHTNESS AND VOLUME
3-DEFAULT FULLSCREEN
4-WHEN PLAYER IS LOADING THEN SHOW A INTERNET SPEED FOR USER

PLEASE ADD THESE FUNCTIONALITY BY THE WAY YOUR PACKAGE IS VERY COOL....THANKS & LOVE FROM INDIA

**Comment by chudongvip** [comment]
> 1-ADD A COVER LOCK
> 2-GESTURE ANIMATION UI FOR BRIGHTNESS AND VOLUME
> 3-DEFAUT FULLSCREEN
> 4-WHEN PLAYER IS LOADING THEN SHOW A INTERNET SPEED FOR USER
> 
> PLEASE ADD THESE FUNCTIONALITY BY THE WAY YOUR PACKAGE IS VERY COOL....THANKS & LOVE FROM INDIA

Dear friend. you can checkout the next branch, i have some method, thanks for your suggests.

**Comment by MeTubeapp** [comment]
ok sir thanks for reply...#STAY SAFE
