### ISSUE TITLE
video ended fill problem

### ISSUE THREAD

**Issue by gulmensedat** [chudongvip/awesome_video_player#41]
how can we fix the image gets stuck on the screen when the video ends?

**Comment by chudongvip** [comment]
> how can we fix the image gets stuck on the screen when the video ends?

you can make the video position to zero.

like this:
```
            /// 视频初始化完成回调
            oninit: (controller) {
              print("video oninit");
              if (controller == null) {
                controller = controller;
              }
            },
            /// 视频播放回调
            onplay: (value) {
              print("video played");
            },
            /// 视频暂停回调
            onpause: (value) {
              print("video paused");
            },
            /// 视频播放结束回调
            onended: (value) {
              print("video ended");
              controller.seekTo(Duration(seconds: 0));
            },
```

**Comment by gulmensedat** [comment]
onended: (value) {
              print("video ended");
              controller.seekTo(Duration(seconds: 0));
            },

controller.seekTo(Duration(seconds: 0));

there is a problem

![Screenshot_114](https://user-images.githubusercontent.com/49756458/83878524-f4820d80-a744-11ea-87f1-1dc4b6e47fce.jpg)

![image](https://user-images.githubusercontent.com/49756458/83880702-395b7380-a748-11ea-974e-3b8c1045f138.jpeg)
![image](https://user-images.githubusercontent.com/49756458/83880710-3f515480-a748-11ea-9d1b-33ff0e44f532.jpeg)

**Comment by chudongvip** [comment]
> onended: (value) {
> print("video ended");
> controller.seekTo(Duration(seconds: 0));
> },
> 
> controller.seekTo(Duration(seconds: 0));
> 
> there is a problem
> 
> ![Screenshot_114](https://user-images.githubusercontent.com/49756458/83878524-f4820d80-a744-11ea-87f1-1dc4b6e47fce.jpg)
> 
> ![image](https://user-images.githubusercontent.com/49756458/83880702-395b7380-a748-11ea-974e-3b8c1045f138.jpeg)
> ![image](https://user-images.githubusercontent.com/49756458/83880710-3f515480-a748-11ea-9d1b-33ff0e44f532.jpeg)

Did you create the variable `controller` on this page?

**Comment by gulmensedat** [comment]
no I could not find?

**Comment by chudongvip** [comment]
> no I could not find?

you can find it in the `onint` callback.

**Comment by gulmensedat** [comment]
> > no I could not find?
> 
> you can find it in the `onint` callback.

It gets 0 okay but it doesn't work for me. The video size changes as soon as the video ends. I want to make BoxFit.contain. While watching the video, it should be the same size as it ends. When the video is over, the duration of the video and whatever time it is found should write.
