### ISSUE TITLE
全屏之后播放器并没有全屏,点击进度条缓冲,视频中没有出现缓冲图标

### ISSUE THREAD

**Issue by 181282945** [chudongvip/awesome_video_player#5]
控件做得很好,还有一点点BUG,全屏之后播放器并没有全屏,点击进度条缓冲,视频中没有出现缓冲图标,真机,安卓10

**Comment by chudongvip** [comment]
你是引入的库，还是github连接？试一下最新的1.0.6

**Comment by 181282945** [comment]
> 你是引入的库，还是github连接？试一下最新的1.0.6
直接引入库的,就是1.0.6版本

**Comment by k3v1n-uncle** [comment]
插件很棒棒！！！
我也是引入库的，1.0.6,安卓9，flutter 1.12.13+hotfix.8，也是不能全屏

**Comment by ghyzx** [comment]
1.0.6,  flutter 1.12.13+hotfix.8， iOS 也是不能全屏

**Comment by 181282945** [comment]
1.0.6+1 貌似还是不能全屏

**Comment by chudongvip** [comment]
把你的版本，手机型号提供一下，或者加QQ群和微信群

**Comment by nearboohood** [comment]
发现用在appBar 中，或者body中有其他控件，纵向不能全屏！报告完毕

**Comment by chudongvip** [comment]
> 发现用在appBar 中，或者body中有其他控件，纵向不能全屏！报告完毕

在`onfullscreen`中根据 flag 去显示或隐藏其他控件

**Comment by nearboohood** [comment]
> > 发现用在appBar 中，或者body中有其他控件，纵向不能全屏！报告完毕
> 
> 在`onfullscreen`中根据 flag 去显示或隐藏其他控件

Offstage Visibility 都不行 同类型的插件   chewie 不会有这个问题

**Comment by chudongvip** [comment]
@181282945 缓冲已经加上了；

@nearboohood @ghyzx @xuwankang  全屏的问题，我都试了，没有问题，我问了群里的都没有出现过，是否可以提供更详细的报告，或者加我微信或者QQ群

**Comment by Maclaon** [comment]
发现用在appBar 中，或者body中有其他控件，纵向不能全屏！报告完毕 任然显示AppBar
