### ISSUE TITLE
为什么视频封面的设置代码‘video cover’被注释掉了？我应该怎么设置视频封面？

### ISSUE THREAD

**Issue by javamr123** [chudongvip/awesome_video_player#52]
我尝试把注释的代码释放，但是没有效果，请问我该怎么设置视频封面？

**Comment by chudongvip** [comment]
> 我尝试把注释的代码释放，但是没有效果，请问我该怎么设置视频封面？

可以尝试 自定义拓展元素
            children: [
              /// 这个将会覆盖的视频内容，因为这个层级是最高级，因此手势会失效(慎用)
              /// 这个可以用来做视频广告
              // Positioned(
              //   top: 0,
              //   left: 0,
              //   bottom: 0,
              //   right: 0,
              //   child: Text("data", style: TextStyle(color: Colors.white),),
              // ),
            ],

**Comment by chudongvip** [comment]
```
/// 自定义拓展元素
            children: [
              /// 这个将会覆盖的视频内容，因为这个层级是最高级，因此手势会失效(慎用)
              /// 这个可以用来做视频广告
              // Positioned(
              //   top: 0,
              //   left: 0,
              //   bottom: 0,
              //   right: 0,
              //   child: Text("data", style: TextStyle(color: Colors.white),),
              // ),
            ],

```
