### ISSUE TITLE
希望可以增加拖动进度提示或这回调，还有播放错误的回调

### ISSUE THREAD

**Issue by Unicellular-SU** [chudongvip/awesome_video_player#8]
项目很棒，是我目前用过的比较好的视频插件，希望可以继续完善👍

**Comment by chudongvip** [comment]
好的，谢谢！我会考虑添加内置的提示以及错误回调；但是拖拽之后进度的提示，请看下面回调
----
拖拽回调：ontimeupdate | 视频播放进度回调（通过返回的value进行字幕匹配）

**Comment by Unicellular-SU** [comment]
> ## 好的，谢谢！我会考虑添加内置的提示以及错误回调；但是拖拽之后进度的提示，请看下面回调
> 拖拽回调：ontimeupdate | 视频播放进度回调（通过返回的value进行字幕匹配）

感谢回复，我看了一下ontimeupdate是实时更新的，可能我表述的不太清楚，我的意思是类似音量和亮度调节，在水平滑动屏幕时，增加一个时间的回调，这样就能显示一个跟随手指移动的时间。目前我已经在您的代码基础上实现了该功能，感谢

**Comment by chudongvip** [comment]
回调是有的，具体参考下面：
onvolume	VideoCallback	播放声音大小变化回调
onbrightness	VideoCallback	屏幕亮度变化回调

**Comment by Unicellular-SU** [comment]
`https://img02.sogoucdn.com/app/a/100520146/b75f93a4666812c48d552c629bcd27cf`
是这种效果，您看一下

**Comment by chudongvip** [comment]
谢谢你的建议，我会完善的，但是你这个连接404，能否给个最新的连接我参考一下

**Comment by Unicellular-SU** [comment]
> 谢谢你的建议，我会完善的，但是你这个连接404，能否给个最新的连接我参考一下

不好意思刚看到消息，[https://s1.ax1x.com/2020/03/18/8DRmgf.gif](url)

**Comment by chudongvip** [comment]
OK，我会加上的，感谢反馈

**Comment by chudongvip** [comment]
版本已更新，发布1.0.6+1，新增拖拽回调
